name: Update S&P 500 Data

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.SP_PAT }}
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas lxml html5lib requests

    - name: Run scraping script
      run: python scrape.py

    - name: Commit and push changes
      run: |
        git config --global user.email "10225173+evollve@users.noreply.github.com"
        git config --global user.name "Evollve"
        git add sp500.json
        git commit -m "Update S&P 500 data" -a || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.SP_PAT }}
